#testing
---
- name: install nginx
  hosts: 192.168.1.62
  become_user: root
  tasks:
        - name: install nginx php7.0 php7.0-fpm roundcube
          apt:
                  name:
                        - nginx
                        - php7.0
                        - php7.0-fpm
                        - roundcube
                  state: present

        - name: download roundcube mail
          get_url:
                   url: https://github.com/roundcube/roundcubemail/releases/download/1.3.7/roundcubemail-1.3.7-complete.tar.gz
                   dest: /var/www/html
                   checksum: sha256:31bd37d0f89dc634064f170c6ed8981c258754b6f81eccb59a2634b29d0bb01c

        - name: decompress roundcube
          unarchive:
            src: /var/www/html/roundcubemail-1.3.7-complete.tar.gz
            dest: /var/www/html

        - name: create directory /var/www/html/roundcubemail-1.3.7
          file:
            path: /var/www/html/roundcubemail-1.3.7
            state: directory
            mode: 0755
            owner: root
            group: mail
            recurse: yes

        - name: copy file to /etc/nginx/sites-enabled
          copy:
           src: /root/playbook-yml/test
           dest: /etc/nginx/sites-enabled

        - name: copy config file to /var/www/html/roundcubemail-1.3.7./config
          copy:
           src: "{{ item.src }}"
           dest: "{{ item.dest }}"
          with_items:
           - { src: /root/playbook-yml/config.inc.php, dest: /var/www/html/roundcubemail-1.3.7/config}
           - { src: /root/playbook-yml/defaults.inc.php, dest: /var/www/html/roundcubemail-1.3.7/config}

        - name: restart nginx.service
          service:
            name: nginx
            state: restarted

            